---
title: "GEOG594:Big Data Science, Lab2"
author: "Harshal Sanap"
date: "September 15, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(ggplot2)
library(reshape2)
library(dplyr)

```

## Basic Statistical Analysis and Visualizations

The data set used for this analysis is Chronic Disease dataset downloaded from <https://data.livewellsd.org/Non-Communicable-Chronic-Disease/Trended-3-4-50-Chronic-Disease/kpde-gmvn>.

## Basic Statistical Operations


```{r Read_data, message=FALSE, warning=FALSE}
disease_data <- read.csv("Trended_3-4-50_Chronic_Disease.csv")
str(disease_data)
head(disease_data)

#Checking out the start and end year for the dataset as:
min(disease_data$Year)
max(disease_data$Year)
```

```{r Stats, message=FALSE, warning=FALSE}
#Quick summary of overall data can be seen as:
summary(disease_data)

#Quick summary only for the latest year of 2013 can be seen as:
sub_data = disease_data[disease_data$Year=="2013",] #Row-slice operation
summary(sub_data)

#Lets checkout distinct regions of San Diego Considered for analysis in this dataset.

unique(disease_data$Geography)




```

## Basic Visualizations

```{r Visualization,message=FALSE, warning=FALSE}
theme_set(theme_bw())
mean_year <- aggregate(disease_data[, c("Stroke.Deaths","CHD.Deaths","Diabetes.Deaths","COPD.Deaths","Asthma.Deaths","Cancer.Deaths","Total.3.4.50.Deaths")],by=list(disease_data$Year), FUN=mean, na.rm=TRUE)

#Below renames the grouped column name Group.1 to Year
names(mean_year)[names(mean_year)=="Group.1"] <- "Year"

#Below function of melt basically used to convert an object to a datafram, I have used it here to consider only 4 variables and id.vars =1 defines the vector of ID variable. e.g in my case it will have first column as Year(id.vars =1) and second column as rest of the variables and third column would be its values

dfm <- melt(mean_year[,c('Year','Stroke.Deaths','Cancer.Deaths','CHD.Deaths')],id.vars = 1) 

#Below ggplot creates a multicolumn bar chart. From this plot we can analyze the trend that Stroke and CHD deaths have decreased from 2000 to 2013 while Cancer deaths have increased

ggplot(dfm,aes(x = Year,y = value)) + 
  geom_bar(aes(fill = variable),stat = "identity",position = "dodge")

```

```{r Visual2}
theme_set(theme_bw())
mean_year_total_deaths <- aggregate(disease_data[, c("Total.Deaths..All.Causes.","Total.3.4.50.Deaths")],by=list(disease_data$Year), FUN=mean, na.rm=TRUE)

names(mean_year_total_deaths)[names(mean_year_total_deaths)=="Group.1"] <- "Year"

#From the below plot we can surprisingly say that the overall total deaths have increased from 2000 till 2013.

g <- ggplot(mean_year_total_deaths,aes(Year,Total.Deaths..All.Causes.))

# Scatterplot
g + geom_point() + 
  geom_smooth(method="lm", se=F) +
  labs(subtitle="Total Deaths trend per year", 
       y="Total Deaths", 
       x="Year", 
       title="Scatterplot with total deaths summarized per year", 
       caption="Source: Live Well San Diego")

#From the below plot we can say that the total deaths count in category of 3-4-50 has decreased from year 2000 till 2013.

g1 <- ggplot(mean_year_total_deaths,aes(Year,Total.3.4.50.Deaths))

# Scatterplot
g1 + geom_point() + 
  geom_smooth(method="lm", se=F) +
  labs(subtitle="Total 3-4-50 Deaths trend per year", 
       y="Total 3-4-50 Deaths", 
       x="Year", 
       title="Scatterplot with total 3-4-50 deaths summarized per year", 
       caption="Source: Live Well San Diego")

```

